'use client';
import { useState } from 'react';
import type { AboutProfile } from '@/types/profile';
import { EvidenceBadge } from '../EvidenceBadge';
export function AboutEditor({ initial, onSave, onCancel }: { initial: AboutProfile; onSave: (profile: AboutProfile) => void; onCancel: () => void }) {
 const [draft, setDraft] = useState(initial);
 return <form className="about-editor" onSubmit={e => { e.preventDefault(); onSave({ ...draft, name: draft.name.trim(), description: draft.description.trim() }); }}><p>Explicitly user-provided. Nothing here is inferred from activity.</p>{(['name', 'description', 'about'] as const).map(key => <label key={key}>{key === 'about' ? 'About Me' : key === 'description' ? 'Short description' : 'Name'}{key === 'about' ? <textarea value={draft[key]} rows={3} maxLength={1000} onChange={e => setDraft({ ...draft, [key]: e.target.value })}/> : <input required={key === 'name'} pattern={key === 'name' ? '.*\\S.*' : undefined} maxLength={key === 'name' ? 60 : 140} value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })}/>}</label>)}{(['interests', 'goals', 'skills', 'values'] as const).map(key => <label key={key}>{key}<small>One item per line</small><textarea rows={4} maxLength={1500} value={draft[key].join('\n')} onChange={e => setDraft({ ...draft, [key]: e.target.value.split('\n') })}/></label>)}<div className="profile-actions"><button type="button" className="profile-button" onClick={onCancel}>Cancel</button><button type="submit" className="profile-button primary">Save profile</button></div></form>;
}
export function ProfileAbout({ profile, showAbout, showInterests, editable, onEdit }: { profile: AboutProfile; showAbout: boolean; showInterests: boolean; editable: boolean; onEdit: () => void }) {
 return <section><div className="section-heading"><div><h2>In your own words</h2><p>About, goals, skills, and values are explicitly user-provided.</p></div>{editable && <button className="profile-button" onClick={onEdit}>Edit About</button>}</div><div className="about-grid">{showAbout && <article className="card sharing-summary"><h2>About Me</h2><p>{profile.about}</p><EvidenceBadge kind="Self-reported"/></article>}{(['interests', 'goals', 'skills', 'values'] as const).map(key => (key === 'interests' ? showInterests : showAbout) && <article key={key} className="card sharing-summary"><h2 className="capitalize">{key}</h2><ul className="about-list">{profile[key].filter(item => item.trim()).map((item, i) => <li key={i}>{item}</li>)}</ul><EvidenceBadge kind="Self-reported"/></article>)}</div>{!showAbout && !showInterests && <div className="card empty-state">About information is not shared with this audience.</div>}</section>;
}
